apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: support-ticket-management-system
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP