apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-pvc
  namespace: support-ticket-management-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi