apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: support-ticket-management-system
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer