apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: support-ticket-management-system
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri /index.html;
        }

        # Proxy pour le backend
        location /api {
          proxy_pass http://backend-service:3000;
        }

        location /images {
          proxy_pass http://backend-service:3000;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
