apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: support-ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: support-ticket-backend:latest 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: backend-env
                